# Site settings
title: Jordans Portfolio
email: Jordan-Huitema@live.nmit.ac.nz
description: Jordan Huitema Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: Jordan.Huitema
github_username: Jordan-Huitema

# Build settings
markdown: kramdown
